project ‘ApplozicSwiftDemo.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'ApplozicSwiftDemo' do
    pod 'ApplozicSwift', :path => '../ApplozicSwift.podspec'
    pod 'Fabric', '~> 1.9.0'
    pod 'Crashlytics', '~> 3.12.0'
end

target 'ApplozicSwiftDemoTests' do
    pod 'ApplozicSwift', :path => '../ApplozicSwift.podspec'
    pod 'Nimble'
    pod 'Quick'
    pod 'Nimble-Snapshots'
end
